name: Unit tests - Required

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
env:
  DATABASE_URL: postgres://cased:shell@127.0.0.1:5536/cased-shell-test
  DOCKER_BUILDKIT: '1'
  BUILDKIT_PROGRESS: 'plain'

jobs:
  pytest:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.6
        env:
          POSTGRES_USER: cased
          POSTGRES_PASSWORD: shell
          POSTGRES_DB: cased-shell-test
        ports:
          - 5536:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.10.x']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          TARGETARCH=${TARGETARCH:-amd64}
          STEP_VERSION=0.20.0
          echo ${TARGETARCH} && curl -LO https://github.com/smallstep/cli/releases/download/v${STEP_VERSION}/step_linux_${STEP_VERSION}_${TARGETARCH}.tar.gz && \
              tar xzvf step_linux_${STEP_VERSION}_${TARGETARCH}.tar.gz && \
              mv step_*/bin/step /usr/local/bin/step && \
              step -version && \
              rm step_linux_${STEP_VERSION}_${TARGETARCH}.tar.gz
      - name: Register Python problem matcher
        run: |
          echo "::add-matcher::.github/workflows/matchers/python.json"
      - name: Install Pytest Annotation plugin
        run: |
          # Ideally this should be part of our dependencies
          # However this plugin is fairly new and doesn't run correctly
          # on a non-GitHub environment.
          pip install pytest-github-actions-annotate-failures==0.1.3
      - name: Register pytest slow test problem matcher
        run: |
          echo "::add-matcher::.github/workflows/matchers/pytest-slow.json"
      - run: coverage run --source=. -m pytest -s --junitxml=tmp/junit.xml
      - name: Detect junit xml
        id: junit
        if: always()
        run: |
          if [ -f tmp/junit.xml ]; then
            echo "::set-output name=path::tmp/junit.xml"
          else
            echo "::set-output name=path::"
          fi
      - name: Generate test Summary
        uses: test-summary/action@v1
        with:
          paths: |
            ${{ steps.junit.outputs.path }}
        if: always() && steps.junit.outputs.path != ''
      - name: Add coverage to test summary
        if: always() && steps.junit.outputs.path != ''
        run: |
          echo "## Coverage" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          coverage report -m >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
